nasa/cmr-metadata-review

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, config/routes.rb
Removed dashboard routes that include extensions (.bk, .1, etc) and sending all bad routing calls to 404 page.
=> Removed dashboard routes that have extension

app/controllers/application_controller.rb
removed rescue_from routing error which no longer works in later version of rails.
=> MMT-1473 - removed rescue_from routing error which no longer works in

app/mailers/curator_mailer.rb, config/environments/development.rb, config/environments/production.rb
* CMRARC-390 The significant change here was in production.rb, it should not use the ENV settings for smtp configuration. Rather letting it default to localhost settings for smtp server seems to work (I tested this in SIT using these settings).
=> Feature/cmrarc 390 (#33)

Gemfile, Gemfile.lock
github complaining about rubyzip gem 1.2.1 and recommends 1.2.2
=> CMRARC-393 updated rubyzip to 1.2.2

app/mailers/curator_mailer.rb, config/environments/development.rb, config/environments/production.rb
Note this is a pull request into master since it is a hot fix.   
Removed configuration value to not perform mail deliveries and just to be sure commented out the code in the mailer class that actually performs the mailing.
=> Removed configuration value to not perform mail deliveries 

Gemfile.lock, app/controllers/login_controller.rb, app/models/acl_dao.rb, app/models/cmr.rb, app/models/user.rb, test/features/can_access_top_page_test.rb
Testing revealed a few issues.  1) If the user is a
daac_curator, an associated daac should be assigned.  Modified the
ACL code to retrieve the daac associated with the daac curator and both are
now assigned to the user.   Note it uses the provider as the daac.
2) Added tests for pulling in daac curators.   Also if it is a daac
added a test to make sure by checking the page you log into, daac curators
don't have a section called "Unreviewed" only arc curators and admins.
Tested for this for their use cases as well.
3) omniauth-urs code was updated in the developer branch and for the gem was being cached, so had to rebuild by clearing the cache on the build machine.
=> CMRARC-418 - Testing revealed a few issues.  1) If the user is a

app/views/layouts/application.html.erb
Charles noticed a reference to an older version of eui, removing as these are imported automatically now.
=> CMRARC-426 removed older eui css reference

app/models/collection.rb, test/controllers/granules_controller_test.rb, test/fixtures/records.yml
the db:reset pull data in a different order, thus needed to have the format field included in the fixture.
=> CMRARC-379 more fixes to broken tests

app/controllers/application_controller.rb, app/models/record.rb, app/views/shared/_records_table.html.erb, test/features/can_revert_record_test.rb, test/features/curator_feedback_test.rb
So it ended up being that the join worked as expected and all the results returned was as expected.   The issue was that the original query to pull in all collection records did this:
`@records = @records.includes(:record_datas).where(record_data: { column_name: ['VersionId', 'Entry_ID/Version', 'Version']}).references(:record_data)`
So this query retrieves all records and includes only record datas where the column name is : `VersionId, Entry_ID/Version, or Version. `
Then in the ERB file it pulled out the version in the table like so:
`<td class="center_text"><%= record.record_datas.first.value%></td>
`
So this rendering makes the assumption that the only record datas included as part of the record is version record data.   When I added feedback data to the query, now we've got record …
=> Feature/cmrarc 369- fixed version field in home table

Gemfile.lock, app/models/collection.rb, lib/CheckerCollection.py
Fixed a minor bug in dashboard where broken urls were throwing an valueerror and this was not caught.  I also increased the timeout since some documents have a lot of urls
=> CMRARC-543 fixed valueerror with bad urls

app/mailers/application_mailer.rb, app/views/daac_curator_mailer/released_records_digest_notification.html.erb, app/views/daac_curator_mailer/released_records_digest_notification.text.erb, config/environments/development.rb, config/environments/production.rb, config/environments/sit.rb, config/environments/test.rb, config/environments/uat.rb, config/schedule.rb, lib/rake_helpers/daac_curator_mailer_helper.rb, test/fixtures/collections.yml, test/fixtures/daac_curator_mailer/released_records_digest_notification_html_part, test/fixtures/daac_curator_mailer/released_records_digest_notification_text_part, test/fixtures/record_data.yml, test/fixtures/records.yml, test/mailers/daac_curator_mailer_test.rb
The Message-ID does not appear to be sufficient to get gmail delivery, but is necessary, so I left the changes in.  The rest of the changes are to accommodate a request to not show granules.
=> Hotfix/CMRARC-545-2 Updating for requested changes and message-id

test/features/curator_feedback_test.rb
removed unnecessary test, as it is now impossible to close a record when it is in feedback.   They must first move the record out of feedback to close it.
=> CMRARC-591 - removed unnecessary test

app/controllers/gkr_keyword_comparison_controller.rb, app/views/gkr_keyword_comparison/show.html.erb, test/features/gkr_keyword_comparison_test.rb
I was able to easily extract the abstract and science keyword values from the collection, which will be needed later on to (1) retrieve recommendations from GKR and (2) compare the keywords from CMR to GKR's recommendations. I then display those on the application. Since I am redirecting to the same view that was rendered originally, I encapsulated the code for displaying the abstract and keywords in if statements to prevent any issues with nil variables.
=> CMRARC-731: Keywords and Abstract successfully pulled from collection

app/models/cmr.rb, app/models/granule.rb, app/models/record_formats/dif10_record.rb, app/models/record_formats/echo10_record.rb, app/views/shared/_footer.html.erb, config/application.rb, data/dif10_required_fields.csv, data/dif10_section_titles.csv, data/echo10_granule_required_fields.csv, data/echo10_granule_section_titles.csv, data/echo10_required_fields.csv, data/ummc_required_fields.csv, db/migrate/20220402153701_include_format_in_echo10_granule_records.rb, db/schema.rb, lib/dashboard_checker.py, lib/dashboard_checker.sh, lib/granule_checker.sh
This PR includes some other fixes as well:
1) When ingesting a random granule, the type of granule was not being set, causing issues downstream
2) Will pull in required fields into the list of desired fields so the list of bubbles includes both required and desired fields.   In testing we noticed some of the required fields were missing, given that they were not in the desired fields list.
3) The pyQuARC version is not added into the footer.
4) A migration rule was added to fix old records that didn't have a type.
5) Code no longer assumes the format with a generic else.
=> feature/CMRARC-772 - ECHO10 granules not ingesting correctly

Gemfile, Gemfile.lock
Deployed CMR Dashboard was complaining about rexml missing. Added it to the Gemfile.
=> CMRARC-798: Adding rexml to gemfile

Gemfile, Gemfile.lock, README.md
To run in daemon mode in the Mac, you'll need to set this env var:
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
Not necessary when just running straight puma though (e.g., rails s)
=> CMRARC-809: Adding pumad to the Gemfile.

app/views/reviews/_navbar.html.erb
When reviewing a file, clicking UMM_JSON will open a new tab. Added target='_blank' to <a> tag.
=> CMRARC-384: Open new tab when clicking ‘UMM-JSON’

app/views/reports/review.html.erb
The button was supposed to say 'export recommendations' not 'export feedback'.
=> CMRARC-813: Fixing verbiage

app/helpers/record_helper.rb, test/controllers/records_controller_test.rb
Previous ticket [CMRARC-579](https://bugs.earthdata.nasa.gov/browse/CMRARC-579) to remove the blocker aspect of this ticket by allowing users to assoc granules from records "closed" even if they didn't pass validation checks (like all fields colored), or only 1 review.
So now CMRARC-582 is to turn back on the validation of closed collection records associating with a granule record to ensure integrity.
I am using this closed collection record as an example because it has only 1 reviewer C43677727-LARC/4
CURRENTLY THE VALIDATION OF CLOSED RECORDS IS BEING TURNED OFF; THEREFORE, WHEN A USER TRIES TO ASSOCIATE A CLOSED COLLECTION RECORD WITH A GRANULE RECORD, THE VALIDATION FOR "Failed to associate granule - Not all columns in the associated granule have been flagged with a color! The …
=> CMRARC-582: Turn back on the validation of closed records to ensure integrity

app/assets/stylesheets/common/_base.scss, app/assets/stylesheets/components/_user_info_box.scss, app/views/shared/_navigation.html.erb
In this ticket, I added User's Guide documentation to the static header of the dashboard. This link opens up in a new tab. To get this to line up the way we would like I ended up cleaning up a bit of the css. Below is a screenshot of the previous static header. 
Here is the new static header with my edits.
=> CMRARC-504: Add Link to Dashboard's User Guide

app/models/multi_record_csv.rb
This is an edit that has been requested for the previous pull request. The only change is that when a user requests to export recommendations, the metric data is removed from the spreadsheet. 
Old Version: 
New Version:
=> CMRARC-813: Removing metric data when irrelevant

package.json, yarn.lock
I needed to add `webpack-cli` and for whatever reason all the webpacker and babel deps could not be dev dependencies, they had to be in the regular deps.
=> CMRARC-850: Updated to package.json in order to deploy to SIT

app/controllers/records_controller.rb
Addressing an issue found in this ticket where umm_json was not accurate for the format. This is a specific use case where the format of umm_json files is actually umm-c. You can see this issue previously addressed in application_helper.rb line 132:
def get_format_and_version(format, version)
version = 'n/a' if version.nil?
format == 'umm_json' ? "umm-c; version=#{version}" : format
end
Before, this format said umm_json in the format column, this fix changes it so that it says umm-c. (Chris, I couldn't use the above function because it would have included the version # as well)
=> CMRACR-843: Formatting for umm_json use case

app/controllers/login_controller.rb, test/controllers/login_controller_test.rb
Currently, when a non-provisioned user tries to login to the Dashboard, they see the following message:
The new change is to update message which is displayed when a non-provisioned user attempts to login to the Dashboard.
=> CMRARC-443: Change Message Viewed by User When Not Provisioned

app/views/reviews/_legend.html.erb
Currently: 
New Change: Legend updated to include a grey circle to say 'No Recommendation' for fields where there is no recommendation made
=> CMRARC-386: As a DAAC curator, I want the collection review details legend to be updated to account for no recommendation

Gemfile.lock, app/assets/stylesheets/pages/_reviews.scss, app/views/reviews/_discussion_and_justification.html.erb, app/views/reviews/_edit_delete_comment.erb, app/views/reviews/_feedback_discussion.html.erb
Here are all the things this ticket addresses (from ticket AC)
1. Scrollbar is removed from Discussion and Justification section 
2. Making edit and delete icons always visible in the comment section
3. Users have ability to edit both comments and recommendations at the same time and save them _There were a few ideas about how best to do this. However the one we decided on was to change the delete alert to save "any unsaved changes will be lost"_
4. Moving comments up and/or flagging when a comment has been left _I opted to move comments up_
5. Excess scroll bars are removed from comment section 
Before: 
After:
=> CMRARC-844: As an ARC curator, I would like to see some general improvements to the Discussion and Justification section

app/models/record.rb, app/views/records/_collection_section_details.html.erb, data/ummc_section_titles.json, test/features/mmt_bubbles_test.rb, test/fixtures/record_data.yml
Reviewing a umm-c record should show sections similar to MMT.
Added the same configuration file that MMT uses for sections and fields to include for each section.   Dashboard now uses this to drive the UI for section/field organization.
Ingest of umm-c records.
View any umm-c record in dashboard, you should see the section/field lists have changed, they now match what is in MMT.
=> CMRARC-820: As a user, I can review a umm-c record where the sections appear similar to MMT.

app/assets/stylesheets/pages/_reviews.scss, app/views/reviews/show.html.erb, test/features/bubble_focus_test.rb
Three issues:
1. The width-resize buttons weren't working
2. update_color_backgrounds() wasn't executing on initial page load
3. Cannot hover over the * to see the acceptable criteria
1. Ended up being a line of .scss called 'content'. Just moved it to another area. Now you can resize the column widths and see the astrick hover-over text. 
2. update_color_backgrounds was too far down the script. It needed to render before other logic came in so I just bumped it up. 
_reviews.scss
the review table when you select a collection >> See Review Detail >> See Collection Review Detail
- **Environment for testing: Local
- **Collection to test with: Whichever you'd like
1. Pull down this branch and run rails s
2. Ingest a collection for review if you don't have one
3. Click through to select a …
=> CMRARC-865: As an ARC Curator, I would like to see three new dashboard bugs fixed

Gemfile, Gemfile.lock
SIT is no longer working. While everything still works locally, it appears that sit is unable to process rexml as per splunk record here:
I, [2024-06-18T17:22:06.274471 #2433550] INFO -- : Completed 500 Internal Server Error in 852ms (ActiveRecord: 9.8ms | Allocations: 8258)
F, [2024-06-18T17:22:06.274979 #2433550] FATAL -- : LoadError (cannot load such file -- rexml/document): app/models/cmr.rb:575:in `collection_search' app/controllers/collections_controller.rb:84:in `search' app/middleware/middleware_healthcheck.rb:14:in `call'
Going to manually install gem 'rexml'
gemfile
- **Environment for testing:**
1. As far as I know, there is no way to test that this works until this fix is up in SIT. 
Please include relevant screenshots or files that would be …
=> CMRARC-866: Adding rexml for SIT issue

yarn.lock
CMR-Dashboard vulnerabilities checked on June 21, 2024
1 high ==> ws
https://github.com/nasa/cmr-metadata-review/security/dependabot/139
Please summarize the feature or fix.
yarn upgrade webpack-dev-server
The vulnerability in the ws package affects the WebSocket implementation used by webpack-dev-server. Specifically, it could impact areas of the application related to development and live reloading.
- **Environment for testing:** Local
1. Step 1
- Checkout CMRARC-870
2. Step 2...
- yarn audit
Result: 0 vulnerabilities found
Before: 
After:
=> CMRARC-870: CMR-Dashboard Vulnerabilities June 2024 (B)

yarn.lock
On master running yarn audit produces the following:
9 vulnerabilities found - Packages audited: 653
Severity: 1 Low | 6 Moderate | 2 High
yarn upgrade webpack-dev-server
yarn.lock file
- **Environment for testing: local
- **Collection to test with: n/a
1. run yarn audit on this branch
2. compare to master
3. PLEASE double check that application runs, my local environment seems to on the fritz so I can't spin it up. 
Master:
This branch:
=> CMRARC-875: CMR-Dashboard Vulnerabilities September 2024

Gemfile.lock, app/views/shared/_footer.html.erb
CMR-Dashboard vulnerabilities checked on March 17, 2025
https://github.com/nasa/cmr-metadata-review/security/dependabot
1 high vulnerability - fix available
#176 https://github.com/nasa/cmr-metadata-review/security/dependabot/176
Name: rack
Version: 2.2.9
CVE: CVE-2025-27610
GHSA: GHSA-7wqh-767x-r66v
Criticality: High
URL: https://github.com/rack/rack/security/advisories/GHSA-7wqh-767x-r66v
Title: Local File Inclusion in Rack::Static
Solution: upgrade to '~> 2.2.13', '~> 3.0.14', '>= 3.1.12'
^^ the slash-through above is just a weird github formatting thing. Version 2.2.13 is recommended for Rails versions 7.x.x.
Ran
$ gem install rack -v 2.2.13
gemfile
- **Environment for testing:**
1. Sanity check to make sure local environment still works
2. Step 2... …
=> CMRARC-882: Fixing high vulnerability

app/models/record.rb, test/features/perform_sanity_checks_on_reviews_test.rb
CMR Dashboard has a duplicate VersionDescription when viewing collection info
Corrected the regex match to match on ending as well. This allows only one column returned at a time.
CMR Dashboard
Login to CMR Dashboard.
Select a record in review. Click on "See Review Detail"
Click "See Collection Review Details"
Click on "Collection Information"
Make sure only 1 VersionDescription column shows up
This shows the issue
This shows the fix
=> CMRARC-789: Fixing duplicate field in CMR Dashboard

app/models/multi_record_csv.rb, app/models/record.rb
Fix the CSVs generated for exported metrics. Currently when there are multiple collections selected, the CSVs generated have duplicate columns and misaligned data.
Removed the duplicated columns and aligned the data properly
Export Metrics for CMR-Dashboard
- **Environment for testing:**
Login to CMR Dashboard. Select 2 collections of the same format in a section. 
Click "Get Review Report"
You will see a button to "EXPORT METRICS". 
Click on the button to generate the CSV file and verify the data in the exported file is aligned properly
(No extra columns at the end, and the proper data is shown under the columns like the color fields)
Please include relevant screenshots or files that would be helpful in reviewing and verifying this change.
Before:
After
=> CMRARC-880: Initial changes to fix exported CSVs
